### PR TITLE
upgrades and testing

### PR DESCRIPTION
**Pull request by tcrowe**
In this PR:
+ npm modules upgraded
+ gulp removed
+ mocha tests added
+ coverage 100%

How to test:

```sh
git clone https://github.com/tcrowe/hexo-browsersync.git
cd hexo-browsersync
git checkout upgrading
npm install
npm test
```

screen shot 2017-11-20 at 7 31 04 am

### CODE REVIEW

**Comment by NoahDragon** [comment]
Thank you for the awesome contribution. One little thing, could you please remove the package-lock.json file?

**Comment by tcrowe** [comment]
Yes @NoahDragon no problem. Do we need a version change? If so, which version?

**Comment by tcrowe** [comment]
Maybe that's best done by the person doing `npm version ...` 😄

**Comment by NoahDragon** [comment]
@tcrowe thank you. Yeah, will let `npm version` to decide. 😄

**Pull request merged**
