### PR TITLE
Update build matrix

### PR DESCRIPTION
**Pull request by tomap**

### CODE REVIEW

**Comment by tomap** [comment]
@hexojs/core appveyor does not seem to be properly configured and running on this project. Could you fix that?

**Comment by tomap** [comment]
Up ?

**Comment by YoshinoriN** [comment]
Maybe I don't have a permission of AppVeyor about hexo repositories. So, I can't check the AppVeyor is work well or not ...

**Comment by NoahDragon** [comment]
I don't think we have linked this project to AppVeyor.

**Comment by tomap** [comment]
I linked it to coveralls and appveyor
Please validate/merge. Thank you

**Pull request merged**
